Repository NavyBye/ft_transcendence, pull requests merged in 2021-05, with the labels that each got.

#95 Feature/frontend ranking
  pong/app/controllers/api/guilds_controller.rb
  pong/app/javascript/srcs/collections/UserRankingCollection.js
  pong/app/javascript/srcs/models/GuildModel.js
  pong/app/javascript/srcs/models/UserModel.js
  pong/app/javascript/srcs/templates/GuildRankingView.html
  pong/app/javascript/srcs/templates/UserRankingView.html
  pong/app/javascript/srcs/views/GuildRankingCollectionView.js
  pong/app/javascript/srcs/views/UserRankingCollectionView.js
  pong/app/javascript/srcs/views/UserRankingView.js
  pong/public/css/content-ranking.css
  pong/test/fixtures/guilds.yml
Labels: frontend

#105 [UPDATE] update github action
  .github/workflows/rails-test.yml
Labels: environments

#116 ban mute 수정 free 추가 / chatroom message pagination 오류 수정
  pong/app/controllers/api/chat_rooms_members_controller.rb
  pong/app/controllers/api/room_messages_controller.rb
  pong/app/jobs/chat_rooms_member_ban_recovery_job.rb
  pong/app/jobs/chat_rooms_member_mute_recovery_job.rb
  pong/app/jobs/chat_rooms_member_recovery_job.rb
  pong/app/models/chat_rooms_member.rb
  pong/config/routes.rb
  pong/db/migrate/20210506050131_change_chat_rooms_members.rb
  pong/db/schema.rb
  pong/test/controllers/api/chat_rooms_members_controller_test.rb
Labels: backend, bug, chat, feature

#151 Feature/backend guild minor fixes
  pong/app/controllers/api/declarations_controller.rb
  pong/app/models/declaration.rb
  pong/app/views/api/declarations/index.json.jbuilder
  pong/config/routes.rb
  pong/test/fixtures/declarations.yml
Labels: backend, guild

#169 Feature/backend guild Declarations
  pong/app/controllers/api/declarations_controller.rb
  pong/test/controllers/api/declarations_controller_test.rb
Labels: backend, guild, test

#179 채팅방 수정, 삭제, 생성됬을 때 시그널 보내기
  pong/app/channels/signal_channel.rb
  pong/app/controllers/api/chat_rooms_controller.rb
  pong/app/helpers/application_helper.rb
  pong/db/schema.rb
Labels: backend
