Repository NavyBye/ft_transcendence, pull requests merged in 2021-04, with the labels that each got.

#4 eslint, prettier, husky, lint-staged 설정
  .husky/.gitignore
  .husky/pre-commit
  .lintstagedrc
  .vscode
  package-lock.json
  package.json
Labels: environments

#10 [UPDATE] install sudo, dockerfile user changed to develop
  Dockerfile
Labels: environments

#11 node 설치 폴더를 바꾸기 위해 도커 파일 수정
  Dockerfile
Labels: environments

#16 #15 이슈 반영
  pong/.rubocop.yml
  pong/config/application.rb
  pong/config/environments/development.rb
  pong/config/initializers/kaminari_config.rb
  pong/package-lock.json
Labels: backend, environments

#19 chatroom api 추가 작업 (진행중)
  pong/app/controllers/api/chat_rooms_controller.rb
  pong/app/controllers/application_controller.rb
  pong/app/models/chat_room.rb
  pong/config/routes.rb
  pong/db/migrate/20210409062240_create_chat_rooms.rb
  pong/test/fixtures/chat_rooms.yml
  pong/test/models/chat_room_test.rb
Labels: backend, chat

#20 ChatRoom CRUD API
  pong/app/controllers/api/chat_rooms_controller.rb
  pong/app/models/chat_room.rb
  pong/db/migrate/20210409062240_create_chat_rooms.rb
  pong/db/schema.rb
  pong/test/controllers/api/chat_rooms_controller_test.rb
  pong/test/fixtures/chat_rooms.yml
  pong/test/models/chat_room_test.rb
Labels: backend, chat

#28 Feature/user 2nd pr to Closes #18
  pong/.rubocop.yml
  pong/Gemfile
  pong/app/assets/stylesheets/api/blocks.scss
  pong/app/assets/stylesheets/api/friends.scss
  pong/app/controllers/api/blocks_controller.rb
  pong/app/controllers/api/friends_controller.rb
  pong/app/controllers/api/users_controller.rb
  pong/app/helpers/api/blocks_helper.rb
  pong/app/helpers/api/friends_helper.rb
  pong/app/models/block.rb
  pong/app/models/friend.rb
  pong/app/models/user.rb
  pong/app/uploaders/user_image_uploader.rb
  pong/app/views/api/blocks/create.html.erb
  pong/app/views/api/blocks/delete.html.erb
  pong/app/views/api/blocks/index.html.erb
  pong/app/views/api/friends/create.html.erb
  pong/app/views/api/friends/destroy.html.erb
  pong/app/views/api/friends/index.html.erb
  pong/config/environment.rb
  pong/config/routes.rb
  pong/db/migrate/20210415055208_add_image_to_users.rb
  pong/db/migrate/20210415075145_create_friends.rb
  pong/db/migrate/20210416061746_create_blocks.rb
  pong/db/migrate/20210416064528_add_unique_index_to_friends.rb
  pong/db/migrate/20210416064659_add_unique_index_to_blocks.rb
  pong/db/schema.rb
  pong/test/controllers/api/blocks_controller_test.rb
  pong/test/controllers/api/friends_controller_test.rb
  pong/test/controllers/api/users_controller_test.rb
  pong/test/controllers/home_controller_test.rb
  pong/test/fixtures/blocks.yml
  pong/test/fixtures/friends.yml
  pong/test/models/block_test.rb
  pong/test/models/friend_test.rb
Labels: backend, feature
